// <auto-generated />
using System;
using AlgebricEquationSystemSolver.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlgebricEquationSystemSolver.DataAccess.Migrations
{
    [DbContext(typeof(AlgebricEquationSystemDbContext))]
    [Migration("20241024155441_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlgebricEquationSystemSolver.DataAccess.Models.AlgebricEquationSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Systems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec1a1b75-11d5-4ec6-9d52-3ddae2eac040"),
                            Parameters = "[1,2,3,4,5,6,7,8,9,10,11,12]"
                        },
                        new
                        {
                            Id = new Guid("239f25ad-6f48-4c01-afb9-66e39313c534"),
                            Parameters = "[10,20,30,40,50,60,72,84,95,10,101,102]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
